### ISSUE TITLE
TypeError: open() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by beheerderdag** [irods-contrib/irods_tools_ingest#8]
I followed the instructions and installed all the necessary components. 
I start the ingest command: 

```
$ ./irodsqueue ingest -f --timer /home/sharifi/irods-test/test.4
```
Then checked the queue that the job is there. Then I start the worker and it fails. Any idea what is going wrong here? 

```
$ for i in {1..2}; do sleep .1; ./rq worker -v --burst -w irodsqueue.irodsworker.IrodsWorker & done

$ 09:44:47 Registering birth of worker irods2.29790
09:44:47 RQ worker 'rq:worker:irods2.29790' started, version 0.9.2
09:44:47 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
09:44:47 Cleaning registries for queue: default
09:44:47 
09:44:47 *** Listening on default...
09:44:47 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
09:44:47 default: irodsqueue.utils.record_start_time(timestamp_id=1) (66ef5ff0-bff1-49ce-9d77-64880e45054a)
09:44:47 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
09:44:47 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
09:44:47 default: Job OK (66ef5ff0-bff1-49ce-9d77-64880e45054a)
09:44:47 Result is kept for 500 seconds
09:44:47 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
09:44:47 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
09:44:47 
09:44:47 *** Listening on default...
09:44:47 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
09:44:47 default: irodsqueue.utils.process_dir('/home/sharifi/irods-test/test.4', namespace(acl=False, chunk_size=8388608, destination='', dry_run=False, exclude='', extract_metadata=None, force=True, prefix='/home/sharifi/irods-test', 
register_checksum=False, source='/home/sharifi/irods-test/test.4', timer=True, verify_checksum=False)) (/home/sharifi/irods-test/test.4)
09:44:47 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
09:44:47 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
09:44:47 process 29790 creating /SURFsaraTest01/home/perf/test.4
09:44:47 Registering birth of worker irods2.29792
09:44:47 RQ worker 'rq:worker:irods2.29792' started, version 0.9.2
09:44:47 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
09:44:47 Cleaning registries for queue: default
09:44:47 
09:44:47 *** Listening on default...
09:44:47 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
09:44:47 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
09:44:47 RQ worker 'rq:worker:irods2.29792' done, quitting
09:44:47 Registering death
09:44:48 default: Job OK (/home/sharifi/irods-test/test.4)
09:44:48 Result is kept for 500 seconds
09:44:48 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
09:44:48 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
09:44:48 
09:44:48 *** Listening on default...
09:44:48 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
09:44:48 default: irodsqueue.utils.process_file('/home/sharifi/irods-test/test.4/file.test.4.3', namespace(acl=False, chunk_size=8388608, destination='', dry_run=False, exclude='', extract_metadata=None, force=True, prefix='/home/sharif
i/irods-test', register_checksum=False, source='/home/sharifi/irods-test/test.4', timer=True, verify_checksum=False)) (/home/sharifi/irods-test/test.4/file.test.4.3)
09:44:48 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
09:44:48 Sent heartbeat to prevent worker timeout. Next one should arrive within 660 seconds.
09:44:48 process 29790 uploading /SURFsaraTest01/home/perf/test.4/file.test.4.3
09:44:48 TypeError: open() takes 3 positional arguments but 4 were given
Traceback (most recent call last):
  File "/usr/local/myVE/testenv3/lib/python3.6/site-packages/rq/worker.py", line 771, in perform_job
    rv = job.perform()
  File "/usr/local/myVE/testenv3/lib/python3.6/site-packages/rq/job.py", line 558, in perform
    self._result = self._execute()
  File "/usr/local/myVE/testenv3/lib/python3.6/site-packages/rq/job.py", line 564, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/local/myVE/testenv3/lib/python3.6/site-packages/irodsqueue/utils.py", line 275, in process_file
    send_file(session, path, target, params)
  File "/usr/local/myVE/testenv3/lib/python3.6/site-packages/irodsqueue/utils.py", line 156, in send_file
    send_chunks(session, file_path, obj_path, params, options)
  File "/usr/local/myVE/testenv3/lib/python3.6/site-packages/irodsqueue/utils.py", line 164, in send_chunks
    with open(file_path, 'rb') as f, session.data_objects.open(obj_path, 'w', options) as o:
TypeError: open() takes 3 positional arguments but 4 were given
Traceback (most recent call last):
  File "/usr/local/myVE/testenv3/lib/python3.6/site-packages/rq/worker.py", line 771, in perform_job
    rv = job.perform()
  File "/usr/local/myVE/testenv3/lib/python3.6/site-packages/rq/job.py", line 558, in perform
    self._result = self._execute()
  File "/usr/local/myVE/testenv3/lib/python3.6/site-packages/rq/job.py", line 564, in _execute
    return self.func(*self.args, **self.kwargs)
  File "/usr/local/myVE/testenv3/lib/python3.6/site-packages/irodsqueue/utils.py", line 275, in process_file
    send_file(session, path, target, params)
  File "/usr/local/myVE/testenv3/lib/python3.6/site-packages/irodsqueue/utils.py", line 156, in send_file
    send_chunks(session, file_path, obj_path, params, options)
  File "/usr/local/myVE/testenv3/lib/python3.6/site-packages/irodsqueue/utils.py", line 164, in send_chunks
    with open(file_path, 'rb') as f, session.data_objects.open(obj_path, 'w', options) as o:
TypeError: open() takes 3 positional arguments but 4 were given
09:44:48 Invoking exception handler <bound method Worker.move_to_failed_queue of <irodsqueue.irodsworker.IrodsWorker object at 0x7fb9c2cf88d0>>
09:44:48 Moving job to 'failed' queue
09:44:48 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
09:44:48 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
[....]


09:44:48 Invoking exception handler <bound method Worker.move_to_failed_queue of <irodsqueue.irodsworker.IrodsWorker object at 0x7fb9c2cf88d0>>
09:44:48 Moving job to 'failed' queue
09:44:48 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
09:44:48 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
09:44:48
09:44:48 *** Listening on default...
09:44:48 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
09:44:48 Sent heartbeat to prevent worker timeout. Next one should arrive within 420 seconds.
09:44:48 RQ worker 'rq:worker:irods2.29790' done, quitting
09:44:48 Registering death

```
My redis queue 

```
127.0.0.1:6379> flushall
OK
(0.81s)
127.0.0.1:6379> keys *
(empty list or set)
127.0.0.1:6379> keys *
 1) "rq:job:/home/sharifi/irods-test/test.4/file.test.4.3"
 2) "rq:job:/home/sharifi/irods-test/test.4:dependents"
 3) "ingest_start_ts_id"
 4) "rq:queues"
 5) "rq:deferred:default"
 6) "rq:queue:default"
 7) "rq:job:/home/sharifi/irods-test/test.4"
 8) "rq:job:/home/sharifi/irods-test/test.4/file.test.4.1:dependents"
 9) "rq:job:9c3231b2-a628-4dcf-8f80-7eb226f9e80a"
10) "rq:job:66ef5ff0-bff1-49ce-9d77-64880e45054a"
11) "rq:job:/home/sharifi/irods-test/test.4/file.test.4.2"
12) "rq:job:/home/sharifi/irods-test/test.4/file.test.4.1"
```

Then later 

```
127.0.0.1:6379> keys *
 1) "rq:job:/home/sharifi/irods-test/test.4/file.test.4.3"
 2) "rq:queues"
 3) "rq:deferred:default"
 4) "rq:worker:irods2.29790"
 5) "rq:worker:irods2.29792"
 6) "rq:job:66ef5ff0-bff1-49ce-9d77-64880e45054a"
 7) "rq:job:/home/sharifi/irods-test/test.4/file.test.4.1"
 8) "ingest_start_ts_id"
 9) "rq:job:/home/sharifi/irods-test/test.4"
10) "rq:job:/home/sharifi/irods-test/test.4/file.test.4.1:dependents"
11) "1"
12) "rq:finished:default"
13) "rq:job:9c3231b2-a628-4dcf-8f80-7eb226f9e80a"
14) "rq:queue:failed"
15) "rq:job:/home/sharifi/irods-test/test.4/file.test.4.2"
```

**Comment by adetorcy** [comment]
I need to update the code following irods/python-irodsclient@7853df4
I will push a fix shortly. In the meantime you can try checking out the previous commit (irods/python-irodsclient@aa5f1e0)

**Comment by beheerderdag** [comment]
Thanks for the fix. Yes, it is working now. I did a small tests and worked. Will do a test with 100,000 small files.
